"""
collect_social_signals.py v2
─────────────────────────────────────────────────────────────────
Monitoruje ogłoszenia o nowych sklepach z:
  1. OLX — ogłoszenia usług SEO / sklep internetowy
  2. RSS agencji wdrożeniowych (Shoper, SkyShop, IdoSell blogi)
  3. RSS branżowych portali e-commerce
  4. GitHub Code Search — sygnatury platform w świeżych plikach

Bez Google Alerts i bez Bing API — zero kluczy zewnętrznych.
GITHUB_TOKEN jest dostępny automatycznie w GitHub Actions.

Wymagania pip: requests feedparser gspread google-auth beautifulsoup4
"""

import os, re, json, time, datetime
import gspread
import requests
import feedparser
from google.oauth2.service_account import Credentials

# ── KONFIGURACJA ─────────────────────────────────────────────

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")

SCOPES = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]
SHEET_QUEUE  = "Kolejka"
# Kolumny zgodne z istniejącym arkuszem:
# A=data_rejestracji, B=domena, C=title, D=strona_dziala, E=url_docelowy,
# F=platforma, G=rejestrator, H=hosting, I=data_rejestracji_whois,
# J=zeskanowano, K=data_skanu, L=zrodlo
HEADER_QUEUE = [
    "data_rejestracji", "domena", "title", "strona_dziala",
    "url_docelowy", "platforma", "rejestrator", "hosting",
    "data_rejestracji_whois", "zeskanowano", "data_skanu", "zrodlo",
]

# ── RSS: AGENCJE + BRANŻOWE ───────────────────────────────────
# Blogi platform i portale e-commerce — case studies nowych wdrożeń,
# newsy o nowych sklepach, wywiady z właścicielami

RSS_FEEDS = [
    # Blogi platform (publikują case studies nowych klientów)
    ("https://www.shoper.pl/blog/feed/",           "Shoper"),
    ("https://sky-shop.pl/blog/feed/",             "SkyShop"),
    ("https://www.idosell.com/pl/blog/rss/",       "IdoSell"),
    ("https://blog.selesto.pl/feed/",              "Selesto"),
    ("https://atomstore.pl/blog/feed/",            "AtomStore"),

    # Portale branżowe e-commerce
    ("https://www.wirtualnemedia.pl/rss/e-commerce.xml",  ""),
    ("https://prnews.pl/rss/kategoria/e-commerce",        ""),
    ("https://eizba.pl/feed/",                            ""),
    ("https://www.sprawnymarketing.pl/feed/",             ""),
    ("https://ecommercepolska.pl/feed/",                  ""),

    # PRowe — nowe otwarcia sklepów często jako komunikaty prasowe
    ("https://www.pap.pl/rss.xml",                        ""),
    ("https://businessinsider.com.pl/feed",               ""),
]

# ── GitHub CODE SEARCH ────────────────────────────────────────
# Świeże pliki HTML/config zawierające sygnatury platform

GITHUB_QUERIES = [
    ('"shoparena.pl"',                              "Shoper"),
    ('"Shoper5_lp"',                                "Shoper"),
    ('"shoperstatic.com"',                          "Shoper"),
    ('"mysky-shop.pl"',                             "SkyShop"),
    ('"Sklep internetowy na oprogramowaniu Sky-Shop"', "SkyShop"),
    ('"var prestashop ="',                          "PrestaShop"),
    ('"automatically generated by PrestaShop"',     "PrestaShop"),
    ('"cdn.idosell.com"',                           "IdoSell"),
    ('"atomstore.pl"',                              "AtomStore"),
    ('"powered by atomstore"',                      "AtomStore"),
    ('"cdn.selesto.pl"',                            "Selesto"),
    ('"takedrop.pl"',                               "TakeDrop"),
    ('"redcart.pl"',                                "RedCart"),
    ('"selly.pl"',                                  "Selly"),
]

# ── OLX QUERIES ───────────────────────────────────────────────
# Szukamy ogłoszeń gdzie właściciel sklepu szuka pomocy (SEO, grafik, itp.)
# — to bezpośredni sygnał że właśnie otworzył sklep

OLX_QUERIES = [
    ("sklep internetowy shoper seo",    "Shoper"),
    ("prestashop sklep seo pozycjonowanie", "PrestaShop"),
    ("sky-shop sklep internetowy",      "SkyShop"),
    ("woocommerce sklep seo",           "WooCommerce"),
    ("nowy sklep internetowy seo",      ""),
    ("pozycjonowanie nowego sklepu",    ""),
    ("sklep shoper pozycjonowanie",     "Shoper"),
    ("sklep prestashop pomoc",          "PrestaShop"),
]

# ── DOMAIN EXTRACTION ─────────────────────────────────────────

DOMAIN_PATTERN = re.compile(
    r'\b(?:https?://)?(?:www\.)?'
    r'([a-z0-9][a-z0-9\-]{1,60}[a-z0-9]'
    r'(?:\.com\.pl|\.net\.pl|\.org\.pl|\.pl|\.eu))'
    r'\b',
    re.IGNORECASE,
)

BLACKLIST = re.compile(
    r'^(shoper\.pl|sky-shop\.pl|prestashop\.com|idosell\.com|'
    r'allegro\.pl|google\.|facebook\.|youtube\.|ceneo\.|olx\.pl|'
    r'wp\.pl|onet\.pl|interia\.pl|gazeta\.pl|tvn24\.pl|'
    r'wirtualnemedia\.pl|prnews\.pl|eizba\.pl)',
    re.IGNORECASE,
)

POLISH_TLDS = (".pl", ".com.pl", ".net.pl", ".org.pl", ".eu")

def extract_domains(text: str) -> list[str]:
    matches = DOMAIN_PATTERN.findall(text)
    result  = []
    for d in matches:
        d = d.lower().rstrip(".")
        if not any(d.endswith(tld) for tld in POLISH_TLDS):
            continue
        if BLACKLIST.search(d):
            continue
        if len(d) < 6:
            continue
        result.append(d)
    return list(dict.fromkeys(result))

# ── ŹRÓDŁO 1: RSS ─────────────────────────────────────────────

def collect_rss() -> list[tuple[str, str, str]]:
    results = []
    cutoff  = datetime.date.today() - datetime.timedelta(days=30)

    for feed_url, platform_hint in RSS_FEEDS:
        try:
            feed = feedparser.parse(feed_url)
            fresh = 0
            for entry in feed.entries:
                pub = entry.get("published_parsed") or entry.get("updated_parsed")
                if pub:
                    pub_date = datetime.date(*pub[:3])
                    if pub_date < cutoff:
                        continue

                text = (entry.get("title", "") + " "
                        + entry.get("summary", "") + " "
                        + entry.get("link", ""))
                domains = extract_domains(text)
                for d in domains:
                    results.append((d, platform_hint, f"rss:{feed_url[:40]}"))
                    fresh += 1

            if fresh:
                print(f"  📰 {feed_url[:50]} → {fresh} kandydatów")
        except Exception as e:
            print(f"  ⚠️  RSS error {feed_url[:40]}: {e}")

    print(f"  RSS łącznie: {len(results)} kandydatów")
    return results

# ── ŹRÓDŁO 2: OLX ─────────────────────────────────────────────

def collect_olx() -> list[tuple[str, str, str]]:
    results = []
    headers = {
        "User-Agent": "Mozilla/5.0 (compatible; EcommerceLeadBot/1.0)",
        "Accept": "application/json",
    }

    for query, platform_hint in OLX_QUERIES:
        try:
            params = {
                "query":   query,
                "sort_by": "created_at:desc",
                "limit":   25,
            }
            r = requests.get(
                "https://www.olx.pl/api/v1/offers/",
                params=params,
                headers=headers,
                timeout=12,
            )
            if r.status_code != 200:
                time.sleep(1)
                continue

            data = r.json()
            for offer in data.get("data", []):
                desc  = offer.get("description", "") or ""
                title = offer.get("title", "")       or ""
                # Też sprawdź URL ogłoszenia po domenę sklepu
                text  = title + " " + desc
                for d in extract_domains(text):
                    results.append((d, platform_hint, "olx"))

            time.sleep(0.8)
        except Exception as e:
            print(f"  ⚠️  OLX error ({query[:30]}): {e}")

    print(f"  OLX: {len(results)} kandydatów")
    return results

# ── ŹRÓDŁO 3: GITHUB CODE SEARCH ─────────────────────────────

def collect_github() -> list[tuple[str, str, str]]:
    if not GITHUB_TOKEN:
        print("  ⚠️  Brak GITHUB_TOKEN — pomijam GitHub (ale w Actions działa auto)")
        return []

    results = []
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    since = (datetime.date.today() - datetime.timedelta(days=30)).isoformat()

    for query, platform_hint in GITHUB_QUERIES:
        try:
            params = {
                "q":        f'{query} pushed:>{since}',
                "per_page": 20,
            }
            r = requests.get(
                "https://api.github.com/search/code",
                headers=headers,
                params=params,
                timeout=15,
            )

            if r.status_code == 403:
                remaining = r.headers.get("X-RateLimit-Remaining", "?")
                print(f"  ⚠️  GitHub rate limit (remaining: {remaining}) — czekam 30s")
                time.sleep(30)
                continue

            if r.status_code != 200:
                print(f"  ⚠️  GitHub HTTP {r.status_code} dla: {query[:40]}")
                time.sleep(2)
                continue

            data  = r.json()
            items = data.get("items", [])

            for item in items:
                # Pobierz raw zawartość pliku (max 5KB)
                raw_url = (item.get("html_url", "")
                           .replace("github.com", "raw.githubusercontent.com")
                           .replace("/blob/", "/"))
                try:
                    rc = requests.get(raw_url, timeout=8,
                                      headers={"Authorization": f"Bearer {GITHUB_TOKEN}"})
                    if rc.status_code == 200:
                        for d in extract_domains(rc.text[:5000]):
                            results.append((d, platform_hint, f"github:{query[:25]}"))
                except Exception:
                    pass

            print(f"  🐙 GitHub '{query[:35]}' → {len(items)} plików")
            time.sleep(2.5)   # szanuj rate limit

        except Exception as e:
            print(f"  ⚠️  GitHub error ({query[:30]}): {e}")

    print(f"  GitHub łącznie: {len(results)} kandydatów")
    return results

# ── GOOGLE SHEETS ─────────────────────────────────────────────

def init_sheets():
    creds = Credentials.from_service_account_info(
        json.loads(os.environ["GOOGLE_CREDENTIALS"]), scopes=SCOPES)
    gc = gspread.authorize(creds)
    sh = gc.open_by_key(os.environ["SPREADSHEET_ID"])

    try:
        ws = sh.worksheet(SHEET_QUEUE)
    except gspread.WorksheetNotFound:
        ws = sh.add_worksheet(title=SHEET_QUEUE, rows=500000, cols=len(HEADER_QUEUE))
        ws.append_row(HEADER_QUEUE)

    existing = set()
    for row in ws.get_all_values()[1:]:
        if row and row[1]:
            existing.add(row[1].strip().lower())

    print(f"  Istniejące w kolejce: {len(existing)} domen")
    return ws, existing

def save_rows(ws, rows: list[list]):
    if not rows:
        return
    BATCH = 200
    for i in range(0, len(rows), BATCH):
        try:
            ws.append_rows(rows[i:i+BATCH], value_input_option="RAW")
        except gspread.exceptions.APIError as e:
            if "429" in str(e):
                time.sleep(60)
                ws.append_rows(rows[i:i+BATCH], value_input_option="RAW")
        if i + BATCH < len(rows):
            time.sleep(2)
    print(f"  💾 Zapisano {len(rows)} nowych domen")

# ── GŁÓWNA FUNKCJA ────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  COLLECT SOCIAL SIGNALS v2 (bez Google Alerts / Bing)")
    print(f"  Start: {datetime.datetime.now().isoformat()}")
    print("=" * 60)

    print("\n🔗 Łączę z Google Sheets...")
    ws, existing = init_sheets()

    today = datetime.date.today().isoformat()
    all_candidates: list[tuple[str, str, str]] = []

    print("\n📰 Źródło 1: RSS (agencje + branżowe)...")
    all_candidates += collect_rss()

    print("\n🛍️  Źródło 2: OLX ogłoszenia...")
    all_candidates += collect_olx()

    print("\n🐙 Źródło 3: GitHub code search...")
    all_candidates += collect_github()

    # Deduplikuj i odfiltruj istniejące
    seen     = set()
    new_rows = []
    best_hint: dict[str, str] = {}

    for domain, platform_hint, source in all_candidates:
        domain = domain.lower().strip()
        if not domain:
            continue
        if domain in existing:
            continue
        if domain in seen:
            # Zaktualizuj hint jeśli mamy lepszy
            if not best_hint.get(domain) and platform_hint:
                best_hint[domain] = platform_hint
            continue

        seen.add(domain)
        best_hint[domain] = platform_hint
        new_rows.append([
            today,
            domain,
            "",            # title
            "",            # strona_dziala
            "",            # url_docelowy
            platform_hint, # F: platforma
            "",            # G: rejestrator
            "",            # H: hosting
            "",            # I: data_rejestracji_whois
            "NIE",         # J: zeskanowano
            "",            # K: data_skanu
            source,        # L: zrodlo
        ])

    print(f"\n📊 Nowych kandydatów: {len(new_rows)}")

    if new_rows:
        save_rows(ws, new_rows)

    # Statystyki źródeł
    from collections import Counter
    source_counter: Counter = Counter()
    for _, _, src in all_candidates:
        source_counter[src.split(":")[0]] += 1

    print("\n📊 Kandydaci wg źródła:")
    for src, n in source_counter.most_common():
        print(f"   {src}: {n}")

    print(f"\n✅ Gotowe. Dodano {len(new_rows)} domen do kolejki.")

if __name__ == "__main__":
    main()
